#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: admin
#    password: password
#    driver-class-name: org.postgresql.Driver
logging.level.org.springframework.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
  jpa:
    show-sql: true
